### ISSUE TITLE
Negative dimension in NDArray.reshape

### ISSUE THREAD

**Issue by gnh1201** [mikera/vectorz#104]
Negative dimension are often used in `numpy` reshape, for example:

```python
np_data = np_data.reshape(-1, 30, 64, 64, 1)
```

but, `vectorz` could not be use it because of `NegativeArraySizeException`.

```java
ndData.reshape(-1, 30, 64, 64, 1); // NegativeArraySizeException
```

Do you have any good ideas or plans?

**Comment by mikera** [comment]
I don't see the rationale for negative dimensions. They don't make logical sense for general-purpose arrays which must have non-negative integer indexes. 

The `numpy` behaviour of inferring the shape from other indexes seems like a hack that doesn't belong in the core library API. If users want this, they can of course implement a higher level reshaping tool that does this.
