### ISSUE TITLE
Question about efficiency

### ISSUE THREAD

**Issue by Real-Septicake** [mikera/vectorz#106]
While I have no doubts about your claim that this is able to do over 1 billion operations per second, I'm curious as to how you managed to determine that.

**Comment by mikera** [comment]
It was a while ago, I did some benchmarks of small in-place vector operations in tight loops using something like JMH I think.

**Comment by Real-Septicake** [comment]
Oh, neat! Much appreciated

**Comment by mikera** [comment]
I can't remember though whether it was number of Vector ops per second or number of element Ops. might have been something like `Vector3.add(Vector3)` in a tight loop?

**Comment by Real-Septicake** [comment]
I don’t know anything about testing efficiency, as could be clearly seen in pretty much every project I’ve put here, and I’m basing my guess entirely on the way you phrased it, but I think it might have been the former.

**Comment by mikera** [comment]
Well benchmarks always vary based on circumstances, I suggest testing in the context of what you need :-)

At the time though, I remember that for small Vector in-place operations it was about as fast as possible for pure Java code. YMMV.
