### ISSUE TITLE
Different implementations of innerProduct for row vs column matrices?

### ISSUE THREAD

**Issue by astanway** [mikera/vectorz#82]
If we compare https://github.com/mikera/vectorz/blob/456c06deeb8de0988e4e18271e908d9b399fb63a/src/main/java/mikera/vectorz/impl/SparseIndexedVector.java#L167 with https://github.com/mikera/vectorz/blob/456c06deeb8de0988e4e18271e908d9b399fb63a/src/main/java/mikera/vectorz/impl/SparseIndexedVector.java#L190, I don't understand why the logic isn't simply to find getRow(i) for SparseRowMatrix like it is for SparseColumnMatrix. Is one of the above methods more efficient than the other?

Aside: if this is not the proper forum for these kinds of questions, let me know! Thanks

**Comment by astanway** [comment]
edit: never mind, it's because you need to get the column regardless of the underlying implementation. So, it's more straightforward to just do this with a getColumn() on a SparseColumnMatrix.

**Comment by mikera** [comment]
It's mainly because repeatedly calling getColumn() is very expensive for a SparseRowMatrix, whereas it is very cheap for a SparseColumnMatrix
