### ISSUE TITLE
Strange exception with join-along

### ISSUE THREAD

**Issue by ysmiraak** [mikera/vectorz#89]
I've been playing with vectorz from core.matrix (thanks for the great work, BTW), and I met this exception with calling `join-along` that I can't understand:

```
(clojure.core.matrix/join-along
 1
 (clojure.core.matrix/array :vectorz [[1 2][3 4][5 6]])
 (clojure.core.matrix/array :vectorz [7 8 9]))
=> IllegalArgumentException Incompatible shapes: [3,2] vs. [3]  mikera.arrayz.impl.JoinedArray.join (JoinedArray.java:33)
```

I don't suppose it was meant to happen? Because I when I did the same thing with `persistent-vector` and also `ndarray-double`, it work out fine:

```
(clojure.core.matrix/join-along 1 [[1 2][3 4][5 6]] [7 8 9])
=> [[1 2 7] [3 4 8] [5 6 9]]
```

I'm using `[net.mikera/core.matrix "0.52.1"]` and `[net.mikera/vectorz-clj "0.44.1"]`.

**Comment by mikera** [comment]
Hi there, join-along expects arguments with compatible dimensions, so you should be doing something like:

``` clojure
(clojure.core.matrix/join-along
    1
    (clojure.core.matrix/array :vectorz [[1 2][3 4][5 6]])
    (clojure.core.matrix/array :vectorz [[7] [8] [9]]))
```

The fact that it works at all for persistent vectors is an implementation quirk, best not to rely on this.

p.s. use `reshape` if you want to get the argument into the correct shape for joining, e.g.:

``` clojure
(reshape [7 8 9] [3 1])
=> [[7] [8] [9]]
```
