### ISSUE TITLE
sparse matrix equality

### ISSUE THREAD

**Issue by malloc82** [mikera/vectorz#90]
Equals function behaves kinda weird for SparseRowMatrix and SparseColumnMatrix. For my problem I need a SparseRowMatrix, but the data are coming in by column. So I store data in SparseColumnMatrix first then use toSparseRowMatrix to convert it to SparseRowMatrix, thinking it maybe faster since I'm using Clojure. However, when I compare the converted SparseRowMatrix with original SparseColumnMatrix using equal function, it keeps giving my false. Here is a simple clojure code for it:

``` Clojure
==> (.equals ^SparseColumnMatrix path-matrix-column (.toSparseRowMatrix ^SparseColumnMatrix path-matrix-column))
==> false
```

The sparse matrix I have is a 40000x41262, and potentially could be much larger. When I tried to create a small matrix manually, say 10x10, and convert it into to the other form, it seems to be ok.

Also, if I convert the sparse column matrix to sparse row matrix then use equality on the sparse row matrix, it gives true:

``` Clojure
==> (def path-matrix-row (.toSparseRowMatrix ^SparseColumnMatrix path-matrix-column))
==> (.equals ^SparseRowMatrix path-matrix-row (.toSparseColumnMatrix ^SparseRowMatrix path-matrix-row))
==> true
```

Also

``` Clojure
==> (.equals ^SparseRowMatrix path-matrix-row ^SparseColumnMatrix path-matrix-column)
==> false ;; returns instantly
==> (equals ^SparseColumnMatrix path-matrix-column ^SparseRowMatrix path-matrix-row)
==> false ;; takes quite a long time
```

**Comment by mikera** [comment]
Thanks for the report.... will take a look. Can you give a minimal example of a matrix that fails?

**Comment by mikera** [comment]
I think I may have a working fix in develop branch, not sure if it addressing exactly your issue though. Feel free to test if you are able to build the snapshot, otherwise I will try to do a new release soon.

**Comment by malloc82** [comment]
Let me try it out.

**Comment by malloc82** [comment]
Just tested it out, it seems to be fine now. Thanks a lot :).

**Comment by malloc82** [comment]
Also the the column to row transform seems to be twice faster for the problem I have. I guess it must be due to the new testVisitNonZero. Bravo!

**Comment by mikera** [comment]
Great, glad it works and thanks for testing! It was good to make this fix, the sparse row/column transform code needed a rewrite in any case :-)

Will make a new release with this fix soon.
