### ISSUE TITLE
Mistake in JoinedArray.get(int x, int y)

### ISSUE THREAD

**Issue by hopeful0** [mikera/vectorz#93]
First, thank you for providing such a highly efficient library. But I found a small mistake in the function `get(int x, int y)`  when I used `JoinedArray`.
```
if ((y<0)||(y>=sliceCount())) {
	throw new IndexOutOfBoundsException(ErrorMessages.invalidIndex(this, x,y));
}
```
The code above has some problem.
`y` should be the second dimension of an array. But `sliceCount()` will return the size of the first dimension of this array.This comparison is easier throwing a exception when  the second dimension larger than the first dimension.

**Comment by hopeful0** [comment]
The current alternative is to use `get(int... index)`. e.g. `get(x,y)`=>`get(new int[]{x,y})`

**Comment by mikera** [comment]
Thanks for the report! I have a fix for this in master
