### ISSUE TITLE
How to serialize a mikera.arrayz.INDArray?

### ISSUE THREAD

**Issue by liujiawinds** [mikera/vectorz#96]
I'm using mikera.arrayz.INDArray in my program. Now I get a problem with INDArray's serialization/ deserialization.

        mikera.arrayz.INDArray data = tensor1.data();

        // fastjson
        //com.alibaba.fastjson.JSONException: write javaBean error, class mikera.matrixx.impl.SparseRowMatrix, Can't slice a scalar!
        com.alibaba.fastjson.JSON.toJSON(data);

        // GSON
        com.google.gson.Gson gson = new Gson();
        // it's ok
        String json = gson.toJson(data);
        // Caused by: java.lang.UnsupportedOperationException: Interface can't be instantiated! Interface name: mikera.arrayz.INDArray
        gson.fromJson(json, INDArray.class);

        // jackson
        ObjectMapper mapper = new ObjectMapper();
        // org.nd4j.shade.jackson.databind.JsonMappingException: Direct self-reference leading to cycle (through reference chain: mikera.matrixx.impl.SparseRowMatrix["rows"]->java.util.ArrayList[0]->mikera.vectorz.impl.SparseIndexedVector["transpose"])
        String json1 = mapper.writeValueAsString(data);

**Comment by mikera** [comment]
Hmmmm I think that's a problem in your serialisation library (i.e. it can't handle reference cycles, or something like that?)

In general, I recommend serialising arrays either by:
- Outputting in a text format (for portability, human readability)
- Outputting the raw `double` data (if performance is a top priority)

**Comment by mikera** [comment]
Other options are to serialise as text, or raw double data using array.toDoubleArray();
