### ISSUE TITLE
Real angles in Vector2 rotateInPlace(), rotate() to copy original

### ISSUE THREAD

**Issue by frankvdh** [mikera/vectorz#97]
Sorry, don't know how to do Git stuff like pull requests... can someone please merge these into the source code? These are amendments to Vector2.java. 
1. rotateInPlace previously took an int angle parameter, which I think is obviously useless
2. Add a new function rotate which returns a rotated copy of the original vector, for convenience.

Frank

	```
/**
	 * Rotates a 2D vector around the origin by a given angle
	 * @param angle
	 */
	public void rotateInPlace(double angle) {
		double ca=Math.cos(angle);
		double sa=Math.sin(angle);
		double nx=(x*ca)-(y*sa);
		double ny=(x*sa)+(y*ca);
		x=nx;
		y=ny;
	}
	
	/**
	 * Rotates a 2D vector around the origin by a given angle
	 * @param angle
   * @return 
	 */
	public Vector2 rotate(double angle) {
		double ca=Math.cos(angle);
		double sa=Math.sin(angle);
    return new Vector2((x*ca)-(y*sa), (x*sa)+(y*ca));
	}

```

**Comment by mikera** [comment]
Thanks for the input, I agree with your suggestions! Just patched this.

FYI I also changed the names to "rotate2D" to avoid confusion with the AVector rotation methods (which rotates elements by a number of places)
