### ISSUE TITLE
Unable to create NDArray for multidimensional arrays

### ISSUE THREAD

**Issue by greeninho** [mikera/vectorz#98]
Good day guys, I have to convert this python code 

    import numpy as np
    x = np.array([[0,6], [1, 2], [3,5], [4,7], [2,9], [10,1]])
    print(x[-4])         # Prints fourth to last [3,5]

 i want to convert to java, so i stumbled upon this library. I made a comparison with nd4j, i found it fast and simple. And since i was unbale to get slice with negative index like the python code work so i decided to try vectorz but i am having problem creating the multidimensional array in vectors. This is what i have done 

    public static void main(String[] args) {
        double[][] x = new double[][]{{0, 6}, {1, 2}, {3, 5}, {4, 7}, {2, 9}, {10, 1}};
        double[] xx = new double[]{0, 6, 1, 2, 3, 5, 4, 7, 2, 9, 10, 1};
        NDArray v=NDArray.wrap(xx, new int[]{2,2});
        System.out.println(v.slice(-4));
    }

So how do I create a NDArray or INDArray from a multidimensional array using vectorz?
and how to slice it to return the same result as the one python gave me?

**Comment by greeninho** [comment]
Ok guys I was able to solve this

        public static void main(String[] args) {
            double[][] x = new double[][]{{0, 6}, {1, 2}, {3, 5}, {4, 7}, {2, 9}, {10, 1}};
            Matrix m = Matrixx.create(x);
            NDArray v=NDArray.wrap(m);
            int size = v.sliceCount();
            System.out.println(v.slice(size-4));
       }

**Comment by ZagButNoZig** [comment]
Maybe close the issue then @greeninho ;)
